// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: state.proto

package core.game.core;

public final class ProtoGameState {
  private ProtoGameState() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:game.core.State)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 stateTime = 1;</code>
     */
    int getStateTime();

    /**
     * <code>repeated .game.core.State.Player players = 7;</code>
     */
    java.util.List<ProtoGameState.State.Player>
        getPlayersList();
    /**
     * <code>repeated .game.core.State.Player players = 7;</code>
     */
    ProtoGameState.State.Player getPlayers(int index);
    /**
     * <code>repeated .game.core.State.Player players = 7;</code>
     */
    int getPlayersCount();
    /**
     * <code>repeated .game.core.State.Player players = 7;</code>
     */
    java.util.List<? extends ProtoGameState.State.PlayerOrBuilder>
        getPlayersOrBuilderList();
    /**
     * <code>repeated .game.core.State.Player players = 7;</code>
     */
    ProtoGameState.State.PlayerOrBuilder getPlayersOrBuilder(
            int index);

    /**
     * <code>repeated .game.core.State.Bullet bullets = 8;</code>
     */
    java.util.List<ProtoGameState.State.Bullet>
        getBulletsList();
    /**
     * <code>repeated .game.core.State.Bullet bullets = 8;</code>
     */
    ProtoGameState.State.Bullet getBullets(int index);
    /**
     * <code>repeated .game.core.State.Bullet bullets = 8;</code>
     */
    int getBulletsCount();
    /**
     * <code>repeated .game.core.State.Bullet bullets = 8;</code>
     */
    java.util.List<? extends ProtoGameState.State.BulletOrBuilder>
        getBulletsOrBuilderList();
    /**
     * <code>repeated .game.core.State.Bullet bullets = 8;</code>
     */
    ProtoGameState.State.BulletOrBuilder getBulletsOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code game.core.State}
   */
  public  static final class State extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:game.core.State)
      StateOrBuilder {
    // Use State.newBuilder() to construct.
    private State(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private State() {
      stateTime_ = 0;
      players_ = java.util.Collections.emptyList();
      bullets_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private State(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              stateTime_ = input.readInt32();
              break;
            }
            case 58: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                players_ = new java.util.ArrayList<ProtoGameState.State.Player>();
                mutable_bitField0_ |= 0x00000002;
              }
              players_.add(
                  input.readMessage(ProtoGameState.State.Player.parser(), extensionRegistry));
              break;
            }
            case 66: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                bullets_ = new java.util.ArrayList<ProtoGameState.State.Bullet>();
                mutable_bitField0_ |= 0x00000004;
              }
              bullets_.add(
                  input.readMessage(ProtoGameState.State.Bullet.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          players_ = java.util.Collections.unmodifiableList(players_);
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          bullets_ = java.util.Collections.unmodifiableList(bullets_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoGameState.internal_static_game_core_State_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoGameState.internal_static_game_core_State_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProtoGameState.State.class, ProtoGameState.State.Builder.class);
    }

    public interface PlayerOrBuilder extends
        // @@protoc_insertion_point(interface_extends:game.core.State.Player)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional string playerId = 1;</code>
       */
      String getPlayerId();
      /**
       * <code>optional string playerId = 1;</code>
       */
      com.google.protobuf.ByteString
          getPlayerIdBytes();

      /**
       * <code>optional float posX = 2;</code>
       */
      float getPosX();

      /**
       * <code>optional float posY = 3;</code>
       */
      float getPosY();

      /**
       * <code>optional int32 viewOr = 4;</code>
       */
      int getViewOr();

      /**
       * <code>optional int32 currWpn = 5;</code>
       */
      int getCurrWpn();

      /**
       * <code>optional int32 health = 6;</code>
       */
      int getHealth();
    }
    /**
     * Protobuf type {@code game.core.State.Player}
     */
    public  static final class Player extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:game.core.State.Player)
        PlayerOrBuilder {
      // Use Player.newBuilder() to construct.
      private Player(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Player() {
        playerId_ = "";
        posX_ = 0F;
        posY_ = 0F;
        viewOr_ = 0;
        currWpn_ = 0;
        health_ = 0;
      }

      @Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
      }
      private Player(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                String s = input.readStringRequireUtf8();

                playerId_ = s;
                break;
              }
              case 21: {

                posX_ = input.readFloat();
                break;
              }
              case 29: {

                posY_ = input.readFloat();
                break;
              }
              case 32: {

                viewOr_ = input.readInt32();
                break;
              }
              case 40: {

                currWpn_ = input.readInt32();
                break;
              }
              case 48: {

                health_ = input.readInt32();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoGameState.internal_static_game_core_State_Player_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoGameState.internal_static_game_core_State_Player_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProtoGameState.State.Player.class, ProtoGameState.State.Player.Builder.class);
      }

      public static final int PLAYERID_FIELD_NUMBER = 1;
      private volatile Object playerId_;
      /**
       * <code>optional string playerId = 1;</code>
       */
      public String getPlayerId() {
        Object ref = playerId_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          playerId_ = s;
          return s;
        }
      }
      /**
       * <code>optional string playerId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getPlayerIdBytes() {
        Object ref = playerId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          playerId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int POSX_FIELD_NUMBER = 2;
      private float posX_;
      /**
       * <code>optional float posX = 2;</code>
       */
      public float getPosX() {
        return posX_;
      }

      public static final int POSY_FIELD_NUMBER = 3;
      private float posY_;
      /**
       * <code>optional float posY = 3;</code>
       */
      public float getPosY() {
        return posY_;
      }

      public static final int VIEWOR_FIELD_NUMBER = 4;
      private int viewOr_;
      /**
       * <code>optional int32 viewOr = 4;</code>
       */
      public int getViewOr() {
        return viewOr_;
      }

      public static final int CURRWPN_FIELD_NUMBER = 5;
      private int currWpn_;
      /**
       * <code>optional int32 currWpn = 5;</code>
       */
      public int getCurrWpn() {
        return currWpn_;
      }

      public static final int HEALTH_FIELD_NUMBER = 6;
      private int health_;
      /**
       * <code>optional int32 health = 6;</code>
       */
      public int getHealth() {
        return health_;
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getPlayerIdBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, playerId_);
        }
        if (posX_ != 0F) {
          output.writeFloat(2, posX_);
        }
        if (posY_ != 0F) {
          output.writeFloat(3, posY_);
        }
        if (viewOr_ != 0) {
          output.writeInt32(4, viewOr_);
        }
        if (currWpn_ != 0) {
          output.writeInt32(5, currWpn_);
        }
        if (health_ != 0) {
          output.writeInt32(6, health_);
        }
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getPlayerIdBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, playerId_);
        }
        if (posX_ != 0F) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(2, posX_);
        }
        if (posY_ != 0F) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(3, posY_);
        }
        if (viewOr_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(4, viewOr_);
        }
        if (currWpn_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(5, currWpn_);
        }
        if (health_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(6, health_);
        }
        memoizedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @Override
      public boolean equals(final Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof ProtoGameState.State.Player)) {
          return super.equals(obj);
        }
        ProtoGameState.State.Player other = (ProtoGameState.State.Player) obj;

        boolean result = true;
        result = result && getPlayerId()
            .equals(other.getPlayerId());
        result = result && (
            Float.floatToIntBits(getPosX())
            == Float.floatToIntBits(
                other.getPosX()));
        result = result && (
            Float.floatToIntBits(getPosY())
            == Float.floatToIntBits(
                other.getPosY()));
        result = result && (getViewOr()
            == other.getViewOr());
        result = result && (getCurrWpn()
            == other.getCurrWpn());
        result = result && (getHealth()
            == other.getHealth());
        return result;
      }

      @Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptorForType().hashCode();
        hash = (37 * hash) + PLAYERID_FIELD_NUMBER;
        hash = (53 * hash) + getPlayerId().hashCode();
        hash = (37 * hash) + POSX_FIELD_NUMBER;
        hash = (53 * hash) + Float.floatToIntBits(
            getPosX());
        hash = (37 * hash) + POSY_FIELD_NUMBER;
        hash = (53 * hash) + Float.floatToIntBits(
            getPosY());
        hash = (37 * hash) + VIEWOR_FIELD_NUMBER;
        hash = (53 * hash) + getViewOr();
        hash = (37 * hash) + CURRWPN_FIELD_NUMBER;
        hash = (53 * hash) + getCurrWpn();
        hash = (37 * hash) + HEALTH_FIELD_NUMBER;
        hash = (53 * hash) + getHealth();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static ProtoGameState.State.Player parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ProtoGameState.State.Player parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ProtoGameState.State.Player parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ProtoGameState.State.Player parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ProtoGameState.State.Player parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static ProtoGameState.State.Player parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static ProtoGameState.State.Player parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static ProtoGameState.State.Player parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static ProtoGameState.State.Player parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static ProtoGameState.State.Player parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(ProtoGameState.State.Player prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @Override
      protected Builder newBuilderForType(
          BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code game.core.State.Player}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:game.core.State.Player)
          ProtoGameState.State.PlayerOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return ProtoGameState.internal_static_game_core_State_Player_descriptor;
        }

        protected FieldAccessorTable
            internalGetFieldAccessorTable() {
          return ProtoGameState.internal_static_game_core_State_Player_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  ProtoGameState.State.Player.class, ProtoGameState.State.Player.Builder.class);
        }

        // Construct using game.core.ProtoGameState.State.Player.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          playerId_ = "";

          posX_ = 0F;

          posY_ = 0F;

          viewOr_ = 0;

          currWpn_ = 0;

          health_ = 0;

          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return ProtoGameState.internal_static_game_core_State_Player_descriptor;
        }

        public ProtoGameState.State.Player getDefaultInstanceForType() {
          return ProtoGameState.State.Player.getDefaultInstance();
        }

        public ProtoGameState.State.Player build() {
          ProtoGameState.State.Player result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public ProtoGameState.State.Player buildPartial() {
          ProtoGameState.State.Player result = new ProtoGameState.State.Player(this);
          result.playerId_ = playerId_;
          result.posX_ = posX_;
          result.posY_ = posY_;
          result.viewOr_ = viewOr_;
          result.currWpn_ = currWpn_;
          result.health_ = health_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof ProtoGameState.State.Player) {
            return mergeFrom((ProtoGameState.State.Player)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(ProtoGameState.State.Player other) {
          if (other == ProtoGameState.State.Player.getDefaultInstance()) return this;
          if (!other.getPlayerId().isEmpty()) {
            playerId_ = other.playerId_;
            onChanged();
          }
          if (other.getPosX() != 0F) {
            setPosX(other.getPosX());
          }
          if (other.getPosY() != 0F) {
            setPosY(other.getPosY());
          }
          if (other.getViewOr() != 0) {
            setViewOr(other.getViewOr());
          }
          if (other.getCurrWpn() != 0) {
            setCurrWpn(other.getCurrWpn());
          }
          if (other.getHealth() != 0) {
            setHealth(other.getHealth());
          }
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          ProtoGameState.State.Player parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (ProtoGameState.State.Player) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private Object playerId_ = "";
        /**
         * <code>optional string playerId = 1;</code>
         */
        public String getPlayerId() {
          Object ref = playerId_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            playerId_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>optional string playerId = 1;</code>
         */
        public com.google.protobuf.ByteString
            getPlayerIdBytes() {
          Object ref = playerId_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            playerId_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string playerId = 1;</code>
         */
        public Builder setPlayerId(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }

          playerId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string playerId = 1;</code>
         */
        public Builder clearPlayerId() {

          playerId_ = getDefaultInstance().getPlayerId();
          onChanged();
          return this;
        }
        /**
         * <code>optional string playerId = 1;</code>
         */
        public Builder setPlayerIdBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

          playerId_ = value;
          onChanged();
          return this;
        }

        private float posX_ ;
        /**
         * <code>optional float posX = 2;</code>
         */
        public float getPosX() {
          return posX_;
        }
        /**
         * <code>optional float posX = 2;</code>
         */
        public Builder setPosX(float value) {

          posX_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional float posX = 2;</code>
         */
        public Builder clearPosX() {

          posX_ = 0F;
          onChanged();
          return this;
        }

        private float posY_ ;
        /**
         * <code>optional float posY = 3;</code>
         */
        public float getPosY() {
          return posY_;
        }
        /**
         * <code>optional float posY = 3;</code>
         */
        public Builder setPosY(float value) {

          posY_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional float posY = 3;</code>
         */
        public Builder clearPosY() {

          posY_ = 0F;
          onChanged();
          return this;
        }

        private int viewOr_ ;
        /**
         * <code>optional int32 viewOr = 4;</code>
         */
        public int getViewOr() {
          return viewOr_;
        }
        /**
         * <code>optional int32 viewOr = 4;</code>
         */
        public Builder setViewOr(int value) {

          viewOr_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 viewOr = 4;</code>
         */
        public Builder clearViewOr() {

          viewOr_ = 0;
          onChanged();
          return this;
        }

        private int currWpn_ ;
        /**
         * <code>optional int32 currWpn = 5;</code>
         */
        public int getCurrWpn() {
          return currWpn_;
        }
        /**
         * <code>optional int32 currWpn = 5;</code>
         */
        public Builder setCurrWpn(int value) {

          currWpn_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 currWpn = 5;</code>
         */
        public Builder clearCurrWpn() {

          currWpn_ = 0;
          onChanged();
          return this;
        }

        private int health_ ;
        /**
         * <code>optional int32 health = 6;</code>
         */
        public int getHealth() {
          return health_;
        }
        /**
         * <code>optional int32 health = 6;</code>
         */
        public Builder setHealth(int value) {

          health_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 health = 6;</code>
         */
        public Builder clearHealth() {

          health_ = 0;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }


        // @@protoc_insertion_point(builder_scope:game.core.State.Player)
      }

      // @@protoc_insertion_point(class_scope:game.core.State.Player)
      private static final ProtoGameState.State.Player DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new ProtoGameState.State.Player();
      }

      public static ProtoGameState.State.Player getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Player>
          PARSER = new com.google.protobuf.AbstractParser<Player>() {
        public Player parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new Player(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Player> parser() {
        return PARSER;
      }

      @Override
      public com.google.protobuf.Parser<Player> getParserForType() {
        return PARSER;
      }

      public ProtoGameState.State.Player getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public interface BulletOrBuilder extends
        // @@protoc_insertion_point(interface_extends:game.core.State.Bullet)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional int32 bulletNum = 1;</code>
       */
      int getBulletNum();

      /**
       * <code>optional float posX = 2;</code>
       */
      float getPosX();

      /**
       * <code>optional float posY = 3;</code>
       */
      float getPosY();

      /**
       * <code>optional int32 damage = 4;</code>
       */
      int getDamage();

      /**
       * <code>optional string ownerId = 7;</code>
       */
      String getOwnerId();
      /**
       * <code>optional string ownerId = 7;</code>
       */
      com.google.protobuf.ByteString
          getOwnerIdBytes();
    }
    /**
     * Protobuf type {@code game.core.State.Bullet}
     */
    public  static final class Bullet extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:game.core.State.Bullet)
        BulletOrBuilder {
      // Use Bullet.newBuilder() to construct.
      private Bullet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Bullet() {
        bulletNum_ = 0;
        posX_ = 0F;
        posY_ = 0F;
        damage_ = 0;
        ownerId_ = "";
      }

      @Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
      }
      private Bullet(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 8: {

                bulletNum_ = input.readInt32();
                break;
              }
              case 21: {

                posX_ = input.readFloat();
                break;
              }
              case 29: {

                posY_ = input.readFloat();
                break;
              }
              case 32: {

                damage_ = input.readInt32();
                break;
              }
              case 58: {
                String s = input.readStringRequireUtf8();

                ownerId_ = s;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoGameState.internal_static_game_core_State_Bullet_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoGameState.internal_static_game_core_State_Bullet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProtoGameState.State.Bullet.class, ProtoGameState.State.Bullet.Builder.class);
      }

      public static final int BULLETNUM_FIELD_NUMBER = 1;
      private int bulletNum_;
      /**
       * <code>optional int32 bulletNum = 1;</code>
       */
      public int getBulletNum() {
        return bulletNum_;
      }

      public static final int POSX_FIELD_NUMBER = 2;
      private float posX_;
      /**
       * <code>optional float posX = 2;</code>
       */
      public float getPosX() {
        return posX_;
      }

      public static final int POSY_FIELD_NUMBER = 3;
      private float posY_;
      /**
       * <code>optional float posY = 3;</code>
       */
      public float getPosY() {
        return posY_;
      }

      public static final int DAMAGE_FIELD_NUMBER = 4;
      private int damage_;
      /**
       * <code>optional int32 damage = 4;</code>
       */
      public int getDamage() {
        return damage_;
      }

      public static final int OWNERID_FIELD_NUMBER = 7;
      private volatile Object ownerId_;
      /**
       * <code>optional string ownerId = 7;</code>
       */
      public String getOwnerId() {
        Object ref = ownerId_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          ownerId_ = s;
          return s;
        }
      }
      /**
       * <code>optional string ownerId = 7;</code>
       */
      public com.google.protobuf.ByteString
          getOwnerIdBytes() {
        Object ref = ownerId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          ownerId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (bulletNum_ != 0) {
          output.writeInt32(1, bulletNum_);
        }
        if (posX_ != 0F) {
          output.writeFloat(2, posX_);
        }
        if (posY_ != 0F) {
          output.writeFloat(3, posY_);
        }
        if (damage_ != 0) {
          output.writeInt32(4, damage_);
        }
        if (!getOwnerIdBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 7, ownerId_);
        }
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (bulletNum_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, bulletNum_);
        }
        if (posX_ != 0F) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(2, posX_);
        }
        if (posY_ != 0F) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(3, posY_);
        }
        if (damage_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(4, damage_);
        }
        if (!getOwnerIdBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, ownerId_);
        }
        memoizedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @Override
      public boolean equals(final Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof ProtoGameState.State.Bullet)) {
          return super.equals(obj);
        }
        ProtoGameState.State.Bullet other = (ProtoGameState.State.Bullet) obj;

        boolean result = true;
        result = result && (getBulletNum()
            == other.getBulletNum());
        result = result && (
            Float.floatToIntBits(getPosX())
            == Float.floatToIntBits(
                other.getPosX()));
        result = result && (
            Float.floatToIntBits(getPosY())
            == Float.floatToIntBits(
                other.getPosY()));
        result = result && (getDamage()
            == other.getDamage());
        result = result && getOwnerId()
            .equals(other.getOwnerId());
        return result;
      }

      @Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptorForType().hashCode();
        hash = (37 * hash) + BULLETNUM_FIELD_NUMBER;
        hash = (53 * hash) + getBulletNum();
        hash = (37 * hash) + POSX_FIELD_NUMBER;
        hash = (53 * hash) + Float.floatToIntBits(
            getPosX());
        hash = (37 * hash) + POSY_FIELD_NUMBER;
        hash = (53 * hash) + Float.floatToIntBits(
            getPosY());
        hash = (37 * hash) + DAMAGE_FIELD_NUMBER;
        hash = (53 * hash) + getDamage();
        hash = (37 * hash) + OWNERID_FIELD_NUMBER;
        hash = (53 * hash) + getOwnerId().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static ProtoGameState.State.Bullet parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ProtoGameState.State.Bullet parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ProtoGameState.State.Bullet parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ProtoGameState.State.Bullet parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ProtoGameState.State.Bullet parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static ProtoGameState.State.Bullet parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static ProtoGameState.State.Bullet parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static ProtoGameState.State.Bullet parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static ProtoGameState.State.Bullet parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static ProtoGameState.State.Bullet parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(ProtoGameState.State.Bullet prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @Override
      protected Builder newBuilderForType(
          BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code game.core.State.Bullet}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:game.core.State.Bullet)
          ProtoGameState.State.BulletOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return ProtoGameState.internal_static_game_core_State_Bullet_descriptor;
        }

        protected FieldAccessorTable
            internalGetFieldAccessorTable() {
          return ProtoGameState.internal_static_game_core_State_Bullet_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  ProtoGameState.State.Bullet.class, ProtoGameState.State.Bullet.Builder.class);
        }

        // Construct using game.core.ProtoGameState.State.Bullet.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          bulletNum_ = 0;

          posX_ = 0F;

          posY_ = 0F;

          damage_ = 0;

          ownerId_ = "";

          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return ProtoGameState.internal_static_game_core_State_Bullet_descriptor;
        }

        public ProtoGameState.State.Bullet getDefaultInstanceForType() {
          return ProtoGameState.State.Bullet.getDefaultInstance();
        }

        public ProtoGameState.State.Bullet build() {
          ProtoGameState.State.Bullet result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public ProtoGameState.State.Bullet buildPartial() {
          ProtoGameState.State.Bullet result = new ProtoGameState.State.Bullet(this);
          result.bulletNum_ = bulletNum_;
          result.posX_ = posX_;
          result.posY_ = posY_;
          result.damage_ = damage_;
          result.ownerId_ = ownerId_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof ProtoGameState.State.Bullet) {
            return mergeFrom((ProtoGameState.State.Bullet)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(ProtoGameState.State.Bullet other) {
          if (other == ProtoGameState.State.Bullet.getDefaultInstance()) return this;
          if (other.getBulletNum() != 0) {
            setBulletNum(other.getBulletNum());
          }
          if (other.getPosX() != 0F) {
            setPosX(other.getPosX());
          }
          if (other.getPosY() != 0F) {
            setPosY(other.getPosY());
          }
          if (other.getDamage() != 0) {
            setDamage(other.getDamage());
          }
          if (!other.getOwnerId().isEmpty()) {
            ownerId_ = other.ownerId_;
            onChanged();
          }
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          ProtoGameState.State.Bullet parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (ProtoGameState.State.Bullet) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private int bulletNum_ ;
        /**
         * <code>optional int32 bulletNum = 1;</code>
         */
        public int getBulletNum() {
          return bulletNum_;
        }
        /**
         * <code>optional int32 bulletNum = 1;</code>
         */
        public Builder setBulletNum(int value) {

          bulletNum_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 bulletNum = 1;</code>
         */
        public Builder clearBulletNum() {

          bulletNum_ = 0;
          onChanged();
          return this;
        }

        private float posX_ ;
        /**
         * <code>optional float posX = 2;</code>
         */
        public float getPosX() {
          return posX_;
        }
        /**
         * <code>optional float posX = 2;</code>
         */
        public Builder setPosX(float value) {

          posX_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional float posX = 2;</code>
         */
        public Builder clearPosX() {

          posX_ = 0F;
          onChanged();
          return this;
        }

        private float posY_ ;
        /**
         * <code>optional float posY = 3;</code>
         */
        public float getPosY() {
          return posY_;
        }
        /**
         * <code>optional float posY = 3;</code>
         */
        public Builder setPosY(float value) {

          posY_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional float posY = 3;</code>
         */
        public Builder clearPosY() {

          posY_ = 0F;
          onChanged();
          return this;
        }

        private int damage_ ;
        /**
         * <code>optional int32 damage = 4;</code>
         */
        public int getDamage() {
          return damage_;
        }
        /**
         * <code>optional int32 damage = 4;</code>
         */
        public Builder setDamage(int value) {

          damage_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 damage = 4;</code>
         */
        public Builder clearDamage() {

          damage_ = 0;
          onChanged();
          return this;
        }

        private Object ownerId_ = "";
        /**
         * <code>optional string ownerId = 7;</code>
         */
        public String getOwnerId() {
          Object ref = ownerId_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            ownerId_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>optional string ownerId = 7;</code>
         */
        public com.google.protobuf.ByteString
            getOwnerIdBytes() {
          Object ref = ownerId_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            ownerId_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string ownerId = 7;</code>
         */
        public Builder setOwnerId(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }

          ownerId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string ownerId = 7;</code>
         */
        public Builder clearOwnerId() {

          ownerId_ = getDefaultInstance().getOwnerId();
          onChanged();
          return this;
        }
        /**
         * <code>optional string ownerId = 7;</code>
         */
        public Builder setOwnerIdBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

          ownerId_ = value;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }


        // @@protoc_insertion_point(builder_scope:game.core.State.Bullet)
      }

      // @@protoc_insertion_point(class_scope:game.core.State.Bullet)
      private static final ProtoGameState.State.Bullet DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new ProtoGameState.State.Bullet();
      }

      public static ProtoGameState.State.Bullet getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Bullet>
          PARSER = new com.google.protobuf.AbstractParser<Bullet>() {
        public Bullet parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new Bullet(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Bullet> parser() {
        return PARSER;
      }

      @Override
      public com.google.protobuf.Parser<Bullet> getParserForType() {
        return PARSER;
      }

      public ProtoGameState.State.Bullet getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int STATETIME_FIELD_NUMBER = 1;
    private int stateTime_;
    /**
     * <code>optional int32 stateTime = 1;</code>
     */
    public int getStateTime() {
      return stateTime_;
    }

    public static final int PLAYERS_FIELD_NUMBER = 7;
    private java.util.List<ProtoGameState.State.Player> players_;
    /**
     * <code>repeated .game.core.State.Player players = 7;</code>
     */
    public java.util.List<ProtoGameState.State.Player> getPlayersList() {
      return players_;
    }
    /**
     * <code>repeated .game.core.State.Player players = 7;</code>
     */
    public java.util.List<? extends ProtoGameState.State.PlayerOrBuilder>
        getPlayersOrBuilderList() {
      return players_;
    }
    /**
     * <code>repeated .game.core.State.Player players = 7;</code>
     */
    public int getPlayersCount() {
      return players_.size();
    }
    /**
     * <code>repeated .game.core.State.Player players = 7;</code>
     */
    public ProtoGameState.State.Player getPlayers(int index) {
      return players_.get(index);
    }
    /**
     * <code>repeated .game.core.State.Player players = 7;</code>
     */
    public ProtoGameState.State.PlayerOrBuilder getPlayersOrBuilder(
        int index) {
      return players_.get(index);
    }

    public static final int BULLETS_FIELD_NUMBER = 8;
    private java.util.List<ProtoGameState.State.Bullet> bullets_;
    /**
     * <code>repeated .game.core.State.Bullet bullets = 8;</code>
     */
    public java.util.List<ProtoGameState.State.Bullet> getBulletsList() {
      return bullets_;
    }
    /**
     * <code>repeated .game.core.State.Bullet bullets = 8;</code>
     */
    public java.util.List<? extends ProtoGameState.State.BulletOrBuilder>
        getBulletsOrBuilderList() {
      return bullets_;
    }
    /**
     * <code>repeated .game.core.State.Bullet bullets = 8;</code>
     */
    public int getBulletsCount() {
      return bullets_.size();
    }
    /**
     * <code>repeated .game.core.State.Bullet bullets = 8;</code>
     */
    public ProtoGameState.State.Bullet getBullets(int index) {
      return bullets_.get(index);
    }
    /**
     * <code>repeated .game.core.State.Bullet bullets = 8;</code>
     */
    public ProtoGameState.State.BulletOrBuilder getBulletsOrBuilder(
        int index) {
      return bullets_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (stateTime_ != 0) {
        output.writeInt32(1, stateTime_);
      }
      for (int i = 0; i < players_.size(); i++) {
        output.writeMessage(7, players_.get(i));
      }
      for (int i = 0; i < bullets_.size(); i++) {
        output.writeMessage(8, bullets_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (stateTime_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, stateTime_);
      }
      for (int i = 0; i < players_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, players_.get(i));
      }
      for (int i = 0; i < bullets_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, bullets_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ProtoGameState.State)) {
        return super.equals(obj);
      }
      ProtoGameState.State other = (ProtoGameState.State) obj;

      boolean result = true;
      result = result && (getStateTime()
          == other.getStateTime());
      result = result && getPlayersList()
          .equals(other.getPlayersList());
      result = result && getBulletsList()
          .equals(other.getBulletsList());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + STATETIME_FIELD_NUMBER;
      hash = (53 * hash) + getStateTime();
      if (getPlayersCount() > 0) {
        hash = (37 * hash) + PLAYERS_FIELD_NUMBER;
        hash = (53 * hash) + getPlayersList().hashCode();
      }
      if (getBulletsCount() > 0) {
        hash = (37 * hash) + BULLETS_FIELD_NUMBER;
        hash = (53 * hash) + getBulletsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ProtoGameState.State parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoGameState.State parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoGameState.State parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoGameState.State parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoGameState.State parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtoGameState.State parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtoGameState.State parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ProtoGameState.State parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtoGameState.State parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtoGameState.State parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ProtoGameState.State prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code game.core.State}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:game.core.State)
        ProtoGameState.StateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoGameState.internal_static_game_core_State_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoGameState.internal_static_game_core_State_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProtoGameState.State.class, ProtoGameState.State.Builder.class);
      }

      // Construct using game.core.ProtoGameState.State.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPlayersFieldBuilder();
          getBulletsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        stateTime_ = 0;

        if (playersBuilder_ == null) {
          players_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          playersBuilder_.clear();
        }
        if (bulletsBuilder_ == null) {
          bullets_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          bulletsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoGameState.internal_static_game_core_State_descriptor;
      }

      public ProtoGameState.State getDefaultInstanceForType() {
        return ProtoGameState.State.getDefaultInstance();
      }

      public ProtoGameState.State build() {
        ProtoGameState.State result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ProtoGameState.State buildPartial() {
        ProtoGameState.State result = new ProtoGameState.State(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.stateTime_ = stateTime_;
        if (playersBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            players_ = java.util.Collections.unmodifiableList(players_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.players_ = players_;
        } else {
          result.players_ = playersBuilder_.build();
        }
        if (bulletsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            bullets_ = java.util.Collections.unmodifiableList(bullets_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.bullets_ = bullets_;
        } else {
          result.bullets_ = bulletsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtoGameState.State) {
          return mergeFrom((ProtoGameState.State)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ProtoGameState.State other) {
        if (other == ProtoGameState.State.getDefaultInstance()) return this;
        if (other.getStateTime() != 0) {
          setStateTime(other.getStateTime());
        }
        if (playersBuilder_ == null) {
          if (!other.players_.isEmpty()) {
            if (players_.isEmpty()) {
              players_ = other.players_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensurePlayersIsMutable();
              players_.addAll(other.players_);
            }
            onChanged();
          }
        } else {
          if (!other.players_.isEmpty()) {
            if (playersBuilder_.isEmpty()) {
              playersBuilder_.dispose();
              playersBuilder_ = null;
              players_ = other.players_;
              bitField0_ = (bitField0_ & ~0x00000002);
              playersBuilder_ =
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPlayersFieldBuilder() : null;
            } else {
              playersBuilder_.addAllMessages(other.players_);
            }
          }
        }
        if (bulletsBuilder_ == null) {
          if (!other.bullets_.isEmpty()) {
            if (bullets_.isEmpty()) {
              bullets_ = other.bullets_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureBulletsIsMutable();
              bullets_.addAll(other.bullets_);
            }
            onChanged();
          }
        } else {
          if (!other.bullets_.isEmpty()) {
            if (bulletsBuilder_.isEmpty()) {
              bulletsBuilder_.dispose();
              bulletsBuilder_ = null;
              bullets_ = other.bullets_;
              bitField0_ = (bitField0_ & ~0x00000004);
              bulletsBuilder_ =
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getBulletsFieldBuilder() : null;
            } else {
              bulletsBuilder_.addAllMessages(other.bullets_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ProtoGameState.State parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ProtoGameState.State) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int stateTime_ ;
      /**
       * <code>optional int32 stateTime = 1;</code>
       */
      public int getStateTime() {
        return stateTime_;
      }
      /**
       * <code>optional int32 stateTime = 1;</code>
       */
      public Builder setStateTime(int value) {

        stateTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 stateTime = 1;</code>
       */
      public Builder clearStateTime() {

        stateTime_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<ProtoGameState.State.Player> players_ =
        java.util.Collections.emptyList();
      private void ensurePlayersIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          players_ = new java.util.ArrayList<ProtoGameState.State.Player>(players_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          ProtoGameState.State.Player, ProtoGameState.State.Player.Builder, ProtoGameState.State.PlayerOrBuilder> playersBuilder_;

      /**
       * <code>repeated .game.core.State.Player players = 7;</code>
       */
      public java.util.List<ProtoGameState.State.Player> getPlayersList() {
        if (playersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(players_);
        } else {
          return playersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .game.core.State.Player players = 7;</code>
       */
      public int getPlayersCount() {
        if (playersBuilder_ == null) {
          return players_.size();
        } else {
          return playersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .game.core.State.Player players = 7;</code>
       */
      public ProtoGameState.State.Player getPlayers(int index) {
        if (playersBuilder_ == null) {
          return players_.get(index);
        } else {
          return playersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .game.core.State.Player players = 7;</code>
       */
      public Builder setPlayers(
          int index, ProtoGameState.State.Player value) {
        if (playersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePlayersIsMutable();
          players_.set(index, value);
          onChanged();
        } else {
          playersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .game.core.State.Player players = 7;</code>
       */
      public Builder setPlayers(
          int index, ProtoGameState.State.Player.Builder builderForValue) {
        if (playersBuilder_ == null) {
          ensurePlayersIsMutable();
          players_.set(index, builderForValue.build());
          onChanged();
        } else {
          playersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .game.core.State.Player players = 7;</code>
       */
      public Builder addPlayers(ProtoGameState.State.Player value) {
        if (playersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePlayersIsMutable();
          players_.add(value);
          onChanged();
        } else {
          playersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .game.core.State.Player players = 7;</code>
       */
      public Builder addPlayers(
          int index, ProtoGameState.State.Player value) {
        if (playersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePlayersIsMutable();
          players_.add(index, value);
          onChanged();
        } else {
          playersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .game.core.State.Player players = 7;</code>
       */
      public Builder addPlayers(
          ProtoGameState.State.Player.Builder builderForValue) {
        if (playersBuilder_ == null) {
          ensurePlayersIsMutable();
          players_.add(builderForValue.build());
          onChanged();
        } else {
          playersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .game.core.State.Player players = 7;</code>
       */
      public Builder addPlayers(
          int index, ProtoGameState.State.Player.Builder builderForValue) {
        if (playersBuilder_ == null) {
          ensurePlayersIsMutable();
          players_.add(index, builderForValue.build());
          onChanged();
        } else {
          playersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .game.core.State.Player players = 7;</code>
       */
      public Builder addAllPlayers(
          Iterable<? extends ProtoGameState.State.Player> values) {
        if (playersBuilder_ == null) {
          ensurePlayersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, players_);
          onChanged();
        } else {
          playersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .game.core.State.Player players = 7;</code>
       */
      public Builder clearPlayers() {
        if (playersBuilder_ == null) {
          players_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          playersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .game.core.State.Player players = 7;</code>
       */
      public Builder removePlayers(int index) {
        if (playersBuilder_ == null) {
          ensurePlayersIsMutable();
          players_.remove(index);
          onChanged();
        } else {
          playersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .game.core.State.Player players = 7;</code>
       */
      public ProtoGameState.State.Player.Builder getPlayersBuilder(
          int index) {
        return getPlayersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .game.core.State.Player players = 7;</code>
       */
      public ProtoGameState.State.PlayerOrBuilder getPlayersOrBuilder(
          int index) {
        if (playersBuilder_ == null) {
          return players_.get(index);  } else {
          return playersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .game.core.State.Player players = 7;</code>
       */
      public java.util.List<? extends ProtoGameState.State.PlayerOrBuilder>
           getPlayersOrBuilderList() {
        if (playersBuilder_ != null) {
          return playersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(players_);
        }
      }
      /**
       * <code>repeated .game.core.State.Player players = 7;</code>
       */
      public ProtoGameState.State.Player.Builder addPlayersBuilder() {
        return getPlayersFieldBuilder().addBuilder(
            ProtoGameState.State.Player.getDefaultInstance());
      }
      /**
       * <code>repeated .game.core.State.Player players = 7;</code>
       */
      public ProtoGameState.State.Player.Builder addPlayersBuilder(
          int index) {
        return getPlayersFieldBuilder().addBuilder(
            index, ProtoGameState.State.Player.getDefaultInstance());
      }
      /**
       * <code>repeated .game.core.State.Player players = 7;</code>
       */
      public java.util.List<ProtoGameState.State.Player.Builder>
           getPlayersBuilderList() {
        return getPlayersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          ProtoGameState.State.Player, ProtoGameState.State.Player.Builder, ProtoGameState.State.PlayerOrBuilder>
          getPlayersFieldBuilder() {
        if (playersBuilder_ == null) {
          playersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              ProtoGameState.State.Player, ProtoGameState.State.Player.Builder, ProtoGameState.State.PlayerOrBuilder>(
                  players_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          players_ = null;
        }
        return playersBuilder_;
      }

      private java.util.List<ProtoGameState.State.Bullet> bullets_ =
        java.util.Collections.emptyList();
      private void ensureBulletsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          bullets_ = new java.util.ArrayList<ProtoGameState.State.Bullet>(bullets_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          ProtoGameState.State.Bullet, ProtoGameState.State.Bullet.Builder, ProtoGameState.State.BulletOrBuilder> bulletsBuilder_;

      /**
       * <code>repeated .game.core.State.Bullet bullets = 8;</code>
       */
      public java.util.List<ProtoGameState.State.Bullet> getBulletsList() {
        if (bulletsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(bullets_);
        } else {
          return bulletsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .game.core.State.Bullet bullets = 8;</code>
       */
      public int getBulletsCount() {
        if (bulletsBuilder_ == null) {
          return bullets_.size();
        } else {
          return bulletsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .game.core.State.Bullet bullets = 8;</code>
       */
      public ProtoGameState.State.Bullet getBullets(int index) {
        if (bulletsBuilder_ == null) {
          return bullets_.get(index);
        } else {
          return bulletsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .game.core.State.Bullet bullets = 8;</code>
       */
      public Builder setBullets(
          int index, ProtoGameState.State.Bullet value) {
        if (bulletsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBulletsIsMutable();
          bullets_.set(index, value);
          onChanged();
        } else {
          bulletsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .game.core.State.Bullet bullets = 8;</code>
       */
      public Builder setBullets(
          int index, ProtoGameState.State.Bullet.Builder builderForValue) {
        if (bulletsBuilder_ == null) {
          ensureBulletsIsMutable();
          bullets_.set(index, builderForValue.build());
          onChanged();
        } else {
          bulletsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .game.core.State.Bullet bullets = 8;</code>
       */
      public Builder addBullets(ProtoGameState.State.Bullet value) {
        if (bulletsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBulletsIsMutable();
          bullets_.add(value);
          onChanged();
        } else {
          bulletsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .game.core.State.Bullet bullets = 8;</code>
       */
      public Builder addBullets(
          int index, ProtoGameState.State.Bullet value) {
        if (bulletsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBulletsIsMutable();
          bullets_.add(index, value);
          onChanged();
        } else {
          bulletsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .game.core.State.Bullet bullets = 8;</code>
       */
      public Builder addBullets(
          ProtoGameState.State.Bullet.Builder builderForValue) {
        if (bulletsBuilder_ == null) {
          ensureBulletsIsMutable();
          bullets_.add(builderForValue.build());
          onChanged();
        } else {
          bulletsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .game.core.State.Bullet bullets = 8;</code>
       */
      public Builder addBullets(
          int index, ProtoGameState.State.Bullet.Builder builderForValue) {
        if (bulletsBuilder_ == null) {
          ensureBulletsIsMutable();
          bullets_.add(index, builderForValue.build());
          onChanged();
        } else {
          bulletsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .game.core.State.Bullet bullets = 8;</code>
       */
      public Builder addAllBullets(
          Iterable<? extends ProtoGameState.State.Bullet> values) {
        if (bulletsBuilder_ == null) {
          ensureBulletsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, bullets_);
          onChanged();
        } else {
          bulletsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .game.core.State.Bullet bullets = 8;</code>
       */
      public Builder clearBullets() {
        if (bulletsBuilder_ == null) {
          bullets_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          bulletsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .game.core.State.Bullet bullets = 8;</code>
       */
      public Builder removeBullets(int index) {
        if (bulletsBuilder_ == null) {
          ensureBulletsIsMutable();
          bullets_.remove(index);
          onChanged();
        } else {
          bulletsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .game.core.State.Bullet bullets = 8;</code>
       */
      public ProtoGameState.State.Bullet.Builder getBulletsBuilder(
          int index) {
        return getBulletsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .game.core.State.Bullet bullets = 8;</code>
       */
      public ProtoGameState.State.BulletOrBuilder getBulletsOrBuilder(
          int index) {
        if (bulletsBuilder_ == null) {
          return bullets_.get(index);  } else {
          return bulletsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .game.core.State.Bullet bullets = 8;</code>
       */
      public java.util.List<? extends ProtoGameState.State.BulletOrBuilder>
           getBulletsOrBuilderList() {
        if (bulletsBuilder_ != null) {
          return bulletsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(bullets_);
        }
      }
      /**
       * <code>repeated .game.core.State.Bullet bullets = 8;</code>
       */
      public ProtoGameState.State.Bullet.Builder addBulletsBuilder() {
        return getBulletsFieldBuilder().addBuilder(
            ProtoGameState.State.Bullet.getDefaultInstance());
      }
      /**
       * <code>repeated .game.core.State.Bullet bullets = 8;</code>
       */
      public ProtoGameState.State.Bullet.Builder addBulletsBuilder(
          int index) {
        return getBulletsFieldBuilder().addBuilder(
            index, ProtoGameState.State.Bullet.getDefaultInstance());
      }
      /**
       * <code>repeated .game.core.State.Bullet bullets = 8;</code>
       */
      public java.util.List<ProtoGameState.State.Bullet.Builder>
           getBulletsBuilderList() {
        return getBulletsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          ProtoGameState.State.Bullet, ProtoGameState.State.Bullet.Builder, ProtoGameState.State.BulletOrBuilder>
          getBulletsFieldBuilder() {
        if (bulletsBuilder_ == null) {
          bulletsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              ProtoGameState.State.Bullet, ProtoGameState.State.Bullet.Builder, ProtoGameState.State.BulletOrBuilder>(
                  bullets_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          bullets_ = null;
        }
        return bulletsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:game.core.State)
    }

    // @@protoc_insertion_point(class_scope:game.core.State)
    private static final ProtoGameState.State DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ProtoGameState.State();
    }

    public static ProtoGameState.State getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<State>
        PARSER = new com.google.protobuf.AbstractParser<State>() {
      public State parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new State(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<State> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<State> getParserForType() {
      return PARSER;
    }

    public ProtoGameState.State getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_game_core_State_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_game_core_State_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_game_core_State_Player_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_game_core_State_Player_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_game_core_State_Bullet_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_game_core_State_Bullet_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\013state.proto\022\tgame.core\"\261\002\n\005State\022\021\n\tst" +
      "ateTime\030\001 \001(\005\022(\n\007players\030\007 \003(\0132\027.game.co" +
      "re.State.Player\022(\n\007bullets\030\010 \003(\0132\027.game." +
      "core.State.Bullet\032g\n\006Player\022\020\n\010playerId\030" +
      "\001 \001(\t\022\014\n\004posX\030\002 \001(\002\022\014\n\004posY\030\003 \001(\002\022\016\n\006vie" +
      "wOr\030\004 \001(\005\022\017\n\007currWpn\030\005 \001(\005\022\016\n\006health\030\006 \001" +
      "(\005\032X\n\006Bullet\022\021\n\tbulletNum\030\001 \001(\005\022\014\n\004posX\030" +
      "\002 \001(\002\022\014\n\004posY\030\003 \001(\002\022\016\n\006damage\030\004 \001(\005\022\017\n\007o" +
      "wnerId\030\007 \001(\tB\020B\016ProtoGameStateb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_game_core_State_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_game_core_State_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_game_core_State_descriptor,
        new String[] { "StateTime", "Players", "Bullets", });
    internal_static_game_core_State_Player_descriptor =
      internal_static_game_core_State_descriptor.getNestedTypes().get(0);
    internal_static_game_core_State_Player_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_game_core_State_Player_descriptor,
        new String[] { "PlayerId", "PosX", "PosY", "ViewOr", "CurrWpn", "Health", });
    internal_static_game_core_State_Bullet_descriptor =
      internal_static_game_core_State_descriptor.getNestedTypes().get(1);
    internal_static_game_core_State_Bullet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_game_core_State_Bullet_descriptor,
        new String[] { "BulletNum", "PosX", "PosY", "Damage", "OwnerId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
